#!/usr/bin/env bash
# Build, deploy, and regenerate bindings for the guess-the-number contract.
#
# Usage:
#   ./scripts/deploy.sh build      # build the WASM only
#   ./scripts/deploy.sh deploy     # deploy to the network in .env
#   ./scripts/deploy.sh bindings   # regenerate TS bindings from the WASM
#   ./scripts/deploy.sh all        # build + deploy + bindings (default)
#   ./scripts/deploy.sh sync-env   # copy .env → frontend-nextjs/.env.local
#
# Reads configuration from .env in the project root.

set -euo pipefail

# Resolve project root (parent of this script's directory).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

# Load .env if present.
if [[ ! -f .env ]]; then
  echo "❌ .env not found at $PROJECT_ROOT/.env"
  echo "   Copy .env.example to .env and fill in the values."
  exit 1
fi

# shellcheck disable=SC1091
set -a
source .env
set +a

# Validate required vars.
required_vars=(
  RPC_URL
  NETWORK_PASSPHRASE
  NETWORK_NAME
  ADMIN_IDENTITY
  XLM_SAC_ADDRESS
)
for var in "${required_vars[@]}"; do
  if [[ -z "${!var:-}" ]]; then
    echo "❌ .env is missing required variable: $var"
    exit 1
  fi
done

WASM_PATH="target/wasm32v1-none/release/guess_the_number.wasm"
BINDINGS_DIR="frontend-nextjs/contracts/guess-the-number"
FRONTEND_ENV="frontend-nextjs/.env.local"

# ---------------------------------------------------------------------------
# build: compile the contract WASM
# ---------------------------------------------------------------------------
cmd_build() {
  echo "🔨 Building contract WASM..."
  stellar contract build \
    --manifest-path contracts/guess-the-number/Cargo.toml
  echo "✅ Built: $WASM_PATH"
}

# ---------------------------------------------------------------------------
# deploy: deploy the WASM to the configured network
# ---------------------------------------------------------------------------
cmd_deploy() {
  if [[ ! -f "$WASM_PATH" ]]; then
    echo "❌ WASM not found at $WASM_PATH — run './scripts/deploy.sh build' first."
    exit 1
  fi

  ADMIN_ADDRESS=$(stellar keys address "$ADMIN_IDENTITY")
  echo "🚀 Deploying to $NETWORK_NAME..."
  echo "   admin: $ADMIN_ADDRESS"
  echo "   xlm:   $XLM_SAC_ADDRESS"

  CONTRACT_ADDRESS=$(
    stellar contract deploy \
      --wasm "$WASM_PATH" \
      --network "$NETWORK_NAME" \
      --source-account "$ADMIN_IDENTITY" \
      -- \
        --admin "$ADMIN_ADDRESS" \
        --xlm   "$XLM_SAC_ADDRESS"
  )

  echo "✅ Deployed: $CONTRACT_ADDRESS"

  # Persist the new address back to .env so subsequent runs pick it up.
  if grep -q '^CONTRACT_ADDRESS=' .env; then
    # macOS sed needs -i ''; Linux needs -i. Detect and use the right form.
    if sed --version >/dev/null 2>&1; then
      sed -i "s|^CONTRACT_ADDRESS=.*|CONTRACT_ADDRESS=$CONTRACT_ADDRESS|" .env
    else
      sed -i '' "s|^CONTRACT_ADDRESS=.*|CONTRACT_ADDRESS=$CONTRACT_ADDRESS|" .env
    fi
  else
    echo "CONTRACT_ADDRESS=$CONTRACT_ADDRESS" >> .env
  fi
  echo "📝 Updated .env with CONTRACT_ADDRESS=$CONTRACT_ADDRESS"

  # Mirror to the frontend env file so the Next.js app picks it up.
  sync_env
}

# ---------------------------------------------------------------------------
# bindings: regenerate the TypeScript bindings from the WASM
# ---------------------------------------------------------------------------
cmd_bindings() {
  if [[ ! -f "$WASM_PATH" ]]; then
    echo "❌ WASM not found at $WASM_PATH — run './scripts/deploy.sh build' first."
    exit 1
  fi

  echo "🔗 Regenerating TypeScript bindings..."
  stellar contract bindings typescript \
    --wasm "$WASM_PATH" \
    --output-dir "$BINDINGS_DIR" \
    --overwrite

  echo "📦 Installing + building the bindings package..."
  (
    cd "$BINDINGS_DIR"
    npm install
    npm run build
  )

  echo "♻️  Refreshing pnpm cache for the bindings package..."
  (
    cd frontend-nextjs
    pnpm update guess-the-number-bindings --force
  )

  echo "✅ Bindings regenerated."
}

# ---------------------------------------------------------------------------
# sync-env: write the NEXT_PUBLIC_* vars the frontend needs into
# frontend-nextjs/.env.local (Next.js convention).
# ---------------------------------------------------------------------------
sync_env() {
  echo "📋 Syncing env → $FRONTEND_ENV..."
  cat > "$FRONTEND_ENV" <<EOF
# Auto-generated by scripts/deploy.sh — do not edit by hand.
# Source of truth: ../.env

NEXT_PUBLIC_RPC_URL=$RPC_URL
NEXT_PUBLIC_NETWORK_PASSPHRASE="$NETWORK_PASSPHRASE"
NEXT_PUBLIC_CONTRACT_ADDRESS=$CONTRACT_ADDRESS
EOF
  echo "✅ Synced."
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------
cmd="${1:-all}"

case "$cmd" in
  build)    cmd_build ;;
  deploy)   cmd_deploy ;;
  bindings) cmd_bindings ;;
  sync-env) sync_env ;;
  all)
    cmd_build
    cmd_deploy
    cmd_bindings
    ;;
  *)
    echo "Usage: $0 {build|deploy|bindings|sync-env|all}"
    exit 1
    ;;
esac